### ISSUE TITLE
[Feat-BE] Scenario API

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/first-repository#15]
In GitLab by @nkyungm on Jul 24, 2024, 05:22

## 📔 Description
- 시나리오 관련 API 개발

## 🐈 Todo

- [ ] 시나리오 목록 조회
- [ ] 좋아요한 시나리오 조회
- [ ] 나의 시나리오 목록 조회
- [ ] 시나리오 상세 정보 조회

**Comment by sook000** [comment]
In GitLab by @nkyungm on Jul 24, 2024, 05:22

created branch [`15-feat-be-scenario-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...15-feat-be-scenario-api) to address this issue

**Comment by sook000** [comment]
In GitLab by @nkyungm on Jul 24, 2024, 17:49

created branch [`15-feat-be-scenario-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...15-feat-be-scenario-api) to address this issue

**Comment by sook000** [comment]
In GitLab by @nkyungm on Jul 24, 2024, 17:54

created branch [`15-feat-be-scenario-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...15-feat-be-scenario-api) to address this issue

**Comment by sook000** [comment]
In GitLab by @nkyungm on Jul 25, 2024, 09:35

mentioned in commit 5cf68f70b0ef0cdee011928a803a1741d7e01292

**Comment by sook000** [comment]
In GitLab by @nkyungm on Jul 25, 2024, 09:41

mentioned in commit e5e8b6f77451c3ad04a5bb35d117e5fde7cca9bb

**Comment by sook000** [comment]
In GitLab by @nkyungm on Jul 27, 2024, 19:49

mentioned in commit 4f2f2c71db32a59fb981f938689aaef3d0e8d90e

**Comment by sook000** [comment]
mentioned in commit 7c14c3db98a7f4d798e8f36da49c2de701289ace

**Comment by sook000** [comment]
mentioned in commit 01d3a64185237cd52ea5cbed9bf3050fc1b250da
