### ISSUE TITLE
[Feat-FE] Action Profile Connection

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/first-repository#35]
In GitLab by @Remnant1318 on Jul 29, 2024, 12:20

[Feat-FE] Action Profile Connection

## 📔 Description
- 액션과 프로필 영역 연결 

## 🐈 Todo

- [ ] 프로필 선택시 직업란 변경(GM)
- [ ] 직업 선택시 액션창 불러오기 
- [ ] 액션들 설명 호버, 모달창 구현

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Jul 29, 2024, 12:20

created branch [`35-feat-fe-action-profile-connection`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...35-feat-fe-action-profile-connection) to address this issue
