### ISSUE TITLE
[Feat-FE] Ingame Profile Action Connection

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/first-repository#45]
In GitLab by @Remnant1318 on Jul 31, 2024, 15:00

## 📔 Description
- 인게임 프로필영역과 액션 연결

## 🐈 Todo

- [ ] 인게임 프로필영역 배경 삽입
- [ ] GM이 인게임 프로필 선택시 액션영역의 목록 변경
- [ ] 액션영역 재 디자인, 목록 변경
- [ ] 액션 영역의 백엔드 Axios 요청 미리 준비하기
- [ ] 액션 선택시 주사위 갯수 자동 변경 로직 작성하기

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Jul 31, 2024, 15:01

created branch [`45-feat-fe-ingame-profile-action-connection`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...45-feat-fe-ingame-profile-action-connection) to address this issue
