### ISSUE TITLE
[Feat-FE]  Ingame Adjustment

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/first-repository#48]
In GitLab by @Remnant1318 on Aug 1, 2024, 12:38

## 📔 Description
- 인게임 컴포넌트 배치들 (비율 재조정)

## 🐈 Todo

- [ ] 인게임 전체 패딩 마진 조정
- [ ] 액션영역 디자인 수정 & 조정
- [ ] 인벤토리 영역 디자인 수정 & 조정
- [ ] 주사위영역 디자인 조정 & 수정
- [ ] 채팅창 디자인 조정 & 수정

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Aug 1, 2024, 12:40

created branch [`48-feat-fe-ingame-adjustment`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...48-feat-fe-ingame-adjustment) to address this issue
