### ISSUE TITLE
[Feat-FE] Inventory and Item Modal

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/first-repository#51]
In GitLab by @Remnant1318 on Aug 2, 2024, 13:01

## 📔 Description
- 인벤토리 컴포넌트 수정 

## 🐈 Todo

- [ ] 인벤토리 배치 재조정
- [ ] 아이템 추가 로직 수정
- [ ] AddItem 모달 추가
- [ ] ItemInfo 모달 추가 
- [ ] ItemInfo 모달에서 횟수 수정, 제거?

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Aug 2, 2024, 13:04

created branch [`51-feat-fe-inventory-and-item-modal`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...51-feat-fe-inventory-and-item-modal) to address this issue
