### ISSUE TITLE
[Feat-FE] Action Modal

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/first-repository#57]
In GitLab by @Remnant1318 on Aug 4, 2024, 22:10

## 📔 Description
- Action Modal

## 🐈 Todo

- [ ] 액션 모달창 구현
- [ ] 액션 모달창에서 선택 누르면 저장 => 주사위 연결 해야한다
- [ ] 캐릭터 인포창에 액션 추가, 보정치 추가

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Aug 4, 2024, 22:10

created branch [`57-feat-fe-action-modal`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...57-feat-fe-action-modal) to address this issue
