### ISSUE TITLE
[Feat-BE] character equipment api

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/first-repository#58]
## 📔 Description
- 캐릭터 장비 crud

## 🐈 Todo

- [x] 캐릭터 장비 목록 조회
- [x] 캐릭터 장비 추가
- [x] 캐릭터 장비 삭제
- [x] 캐릭터 장비 수량 바꾸기

**Comment by sook000** [comment]
created branch [`58-feat-be-character-equipment-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...58-feat-be-character-equipment-api) to address this issue

**Comment by sook000** [comment]
mentioned in commit 0d993f953bd92551537787d74071aa04a5a34b02

**Comment by sook000** [comment]
created branch [`58-feat-be-character-equipment-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...58-feat-be-character-equipment-api) to address this issue

**Comment by sook000** [comment]
marked the checklist item **캐릭터 장비 목록 조회** as completed

**Comment by sook000** [comment]
marked the checklist item **캐릭터 장비 추가** as completed

**Comment by sook000** [comment]
marked the checklist item **캐릭터 장비 삭제** as completed

**Comment by sook000** [comment]
mentioned in commit 21fdbea9e01b50348c141c21efcd30959a547aa8

**Comment by sook000** [comment]
created branch [`58-feat-be-character-equipment-api`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...58-feat-be-character-equipment-api) to address this issue

**Comment by sook000** [comment]
mentioned in commit c9fd36836e98a558e8fabf000305c1495e24ddee

**Comment by sook000** [comment]
marked the checklist item **캐릭터 장비 수량 바꾸기** as completed

**Comment by sook000** [comment]
mentioned in commit f6f6fdb2afe0993fd60f403e7bdbd7d18e8d0ca2
