### ISSUE TITLE
[Feat-FE] Ingame API Connection

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/first-repository#66]
In GitLab by @Remnant1318 on Aug 7, 2024, 23:13

## 📔 Description
- 인게임 API 연동

## 🐈 Todo

- [ ] 더미데이터 넣어서 연동확인
- [ ] 각 캐릭터 스탯 연동
- [ ] 캐릭터 인포모달 연동
- [ ] 인벤토리 연동
- [ ] 액션연동

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Aug 7, 2024, 23:13

created branch [`66-feat-fe-ingame-api-connection`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...66-feat-fe-ingame-api-connection) to address this issue

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Aug 9, 2024, 17:56

mentioned in commit 3eca2134d10973a2bd514b9902e9963e0180bc9f

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Aug 9, 2024, 18:04

mentioned in commit a14b465798d888be330f535b7b932dfb686e9e07

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Nov 26, 2024, 14:21

mentioned in commit 139686bfe85590475421a070a7b05dc39be5402e

**Comment by sook000** [comment]
In GitLab by @Remnant1318 on Nov 26, 2024, 14:21

mentioned in commit d456672d801fdc4bfa8d545534d068e5188e2b17
