### ISSUE TITLE
[Feat-FE] MyPage

### ISSUE THREAD

**Issue by sook000** [sixtale-trpg/first-repository#69]
## 📔 Description
- 마이페이지 디자인 구현

## 🐈 Todo

- [x] 마이페이지 틀 잡기
- [x] 마이페이지 닉네임, 사진 연동하기
- [x] 플레이 기록 페이지
- [ ] 플레이 일정 페이지
- [ ] 좋아요한 시나리오
- [ ] 정보 조회/수정
- [ ] 성향 시트

**Comment by sook000** [comment]
created branch [`69-feat-fe-mypage`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...69-feat-fe-mypage) to address this issue

**Comment by sook000** [comment]
mentioned in commit 1aeba6401ed02114e4972d985fa923ced6f05877

**Comment by sook000** [comment]
created branch [`69-feat-fe-mypage`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...69-feat-fe-mypage) to address this issue

**Comment by sook000** [comment]
created branch [`69-feat-fe-mypage`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...69-feat-fe-mypage) to address this issue

**Comment by sook000** [comment]
mentioned in commit 4dff6d47764dd3d5aca924c57213206442ee4d14

**Comment by sook000** [comment]
created branch [`69-feat-fe-mypage`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...69-feat-fe-mypage) to address this issue

**Comment by sook000** [comment]
mentioned in commit d8291aae5796100162d7b68b7c19075bda13d402

**Comment by sook000** [comment]
marked the checklist item **마이페이지 디자인 구현** as completed

**Comment by sook000** [comment]
created branch [`69-feat-fe-mypage`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...69-feat-fe-mypage) to address this issue

**Comment by sook000** [comment]
mentioned in commit e46feb0ec4dda264796b5bdca5615b332dc6788a

**Comment by sook000** [comment]
mentioned in commit a6151c5f56696f251b4ae59a1362d1f592e7541f

**Comment by sook000** [comment]
created branch [`69-feat-fe-mypage`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...69-feat-fe-mypage) to address this issue

**Comment by sook000** [comment]
created branch [`69-feat-fe-mypage`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...69-feat-fe-mypage) to address this issue

**Comment by sook000** [comment]
mentioned in commit 65b2608155dc3631dbf0123b55ab630e78996e79

**Comment by sook000** [comment]
In GitLab by @singunu on Aug 13, 2024, 23:02

created branch [`69-feat-fe-mypage`](/s11-webmobile1-sub2/S11P12D108/-/compare/master...69-feat-fe-mypage) to address this issue

**Comment by sook000** [comment]
mentioned in commit 4ff81aa35883ae7dff5dd8f3f8ee8cb83996a76f

**Comment by sook000** [comment]
mentioned in commit 5f4f4e9be9328a1c2dab0348ff1637853532cd5d

**Comment by sook000** [comment]
mentioned in commit 7eab917e19ceafb5f1f2128081b2657c6c467a9a

**Comment by sook000** [comment]
mentioned in commit a8acddc111d3ac12babfb705ccda23cc5e903bd0

**Comment by sook000** [comment]
mentioned in commit 01fc8f8ea75215ff034689d66eadb1a6e08cc7df
